### ISSUE TITLE
Choose S3 signer version

### ISSUE THREAD

**Issue by waxzce** [Kaliber/play-s3#32]
Hi

Is it possible to choose the S3 signer version, my backend only support previous ATM

**Comment by lukaswelte** [comment]
Would be awesome to have since riak cs does still not support AWS 4 authentication.
Anybody did work on this? @waxzce @EECOLOR?

**Comment by waxzce** [comment]
My fork should support it, but it's ugly...
If it doesn't, i can push the crapy things we build on a project...

But the point is : using AWS sdk is more simple in this case

**Comment by lukaswelte** [comment]
Thanks for the informations, @waxzce.
Using the AWS SDK is what I did to accomplish my works. Although play-s3 provides a neat api for s3, using the official supported one feels a little more safe and future proof.

**Comment by EECOLOR** [comment]
It should be a lot easier to support in the `6.0.0` branch: https://github.com/Rhinofly/play-s3/tree/6.0.0

We might be able to use the old Aws3Signer for inspiration: https://github.com/Rhinofly/play-aws-utils/blob/v2.4.2/app/fly/play/aws/auth/Aws3Signer.scala

As you might have noticed, my time to work on this project is very limited

**Comment by EECOLOR** [comment]
We are not going to add this feature.

If there is any interest in an `Aws3Signer`, feel free to contribute. The following files can be used as a starting point:

[S3Signer.scala](https://github.com/Kaliber/play-s3/blob/9abdac7fd45050b396de84fdb701cd511d9939ba/app/fly/play/s3/S3Signer.scala)
[S3SignerSpec](https://github.com/Kaliber/play-s3/blob/9abdac7fd45050b396de84fdb701cd511d9939ba/test/fly/play/s3/S3SignerSpec.scala)
[Signer](https://github.com/Rhinofly/play-aws-utils/blob/v2.4.2/app/fly/play/aws/auth/Signer.scala)

The interface to implement is: [AwsSigner](https://github.com/Kaliber/play-s3/blob/master/src/main/scala/fly/play/aws/AwsSigner.scala)

Note that the [S3Signer](https://github.com/Kaliber/play-s3/blob/master/src/main/scala/fly/play/s3/S3Signer.scala) class should use composition instead of inheritance to support another signer.
