### ISSUE TITLE
Updating Header Information

### ISSUE THREAD

**Issue by neilchaudhuri** [Kaliber/play-s3#57]
Is it possible to update the header information for a key without removing the key and replacing it with the same content but new headers?

Thanks.

**Comment by EECOLOR** [comment]
Maybe using the `x-amz-metadata-directive`, see http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html#RESTObjectCOPY-requests-request-parameters.

First google result was: http://stackoverflow.com/questions/269840/is-it-possible-to-change-headers-on-an-s3-object-without-downloading-the-entire

**Comment by neilchaudhuri** [comment]
Right, I know it is theoretically possible using the S3 API directly. I was just curious if play-s3 offered any kind of abstraction or if you had any suggestion beyond the standard guidance. Besides, that SO post is from 2008. Back then, there had only been one Transformers movie. That's how long ago it was.

Thanks.

**Comment by EECOLOR** [comment]
Haha, I didn't even notice it was that old.

I haven't tried it myself. But you could check the [`S3.putCopy`](https://github.com/Kaliber/play-s3/blob/master/src/main/scala/fly/play/s3/S3.scala#L190) method. Otherwise you could grab an [`S3Client`](https://github.com/Kaliber/play-s3/blob/master/src/main/scala/fly/play/s3/S3Client.scala) which is essentially just a `WSClient` and thus gives you all freedom in the world.

**Comment by EECOLOR** [comment]
If you think we should have an extra abtraction on `S3` or `Bucket` file a pull request or open an issue :-)
