### ISSUE TITLE
Don't map results through `unitResponse` to allow logging of errors

### ISSUE THREAD

**Issue by raphael-proust** [Kaliber/play-s3#59]
Every response is mapped through `unitResponse`. Whilst it simplifies the return types, it prevents any form of error management.

There are several solutions:
- Let the response through
- Allow the users to pass a continuation as an optional argument (default to `unitResponse`)
- Others?

**Comment by EECOLOR** [comment]
I most certainly agree with you here. That must have been in there since the beginning. I would suggest using an implicit with a default value. That would keep it source compatible.

Please note that my time at the moment is extremely limited. Feel free to open up some pull requests. If I can squeeze in a few minutes I would be able to review them.

**Comment by raphael-proust** [comment]
I'll try to do that soon.

**Comment by n0tel** [comment]
@raphael-proust Hello. When approximately you expect to implement it?

**Comment by raphael-proust** [comment]
@n0tel haven't gotten around to it yet. I'm part time on the scala-play project and not working on it right now. If you want to have a go, you can.

**Comment by EECOLOR** [comment]
I just had some time to dive into the code.

You can use the usual methods of recovering from failing futures. Something like this would work:

```
bucketResult.recover {
  case S3Exception(status, code, message, originalXml) => ...
}
```

The signature of the `S3Exception` case class:

```
case class S3Exception(status: Int, code: String, message: String, originalXml: Option[Elem])
```

I am closing this issue. If this is too limiting, please reopen the issue with extra information.
